// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: marketplace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error codes used across the service
type ErrorCode int32

const (
	// System errors (1xxx)
	ErrorCode_ERROR_INTERNAL            ErrorCode = 0 // 1000: Unexpected internal server error
	ErrorCode_ERROR_NOT_IMPLEMENTED     ErrorCode = 1 // 1001: Feature not yet implemented
	ErrorCode_ERROR_SERVICE_UNAVAILABLE ErrorCode = 2 // 1002: Service temporarily unavailable
	// Request errors (2xxx)
	ErrorCode_ERROR_INVALID_REQUEST      ErrorCode = 3 // 2000: Malformed or invalid request
	ErrorCode_ERROR_INVALID_CONTENT_TYPE ErrorCode = 4 // 2001: Unsupported content type
	ErrorCode_ERROR_VALIDATION           ErrorCode = 5 // 2002: Request validation failed
	ErrorCode_ERROR_UNAUTHORIZED         ErrorCode = 6 // 2003: Authentication required
	ErrorCode_ERROR_FORBIDDEN            ErrorCode = 7 // 2004: Insufficient permissions
	// Resource errors (3xxx)
	ErrorCode_ERROR_NOT_FOUND         ErrorCode = 8  // 3000: Requested resource not found
	ErrorCode_ERROR_ALREADY_EXISTS    ErrorCode = 9  // 3001: Resource already exists
	ErrorCode_ERROR_RESOURCE_CONFLICT ErrorCode = 10 // 3002: Resource state conflict
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_INTERNAL",
		1:  "ERROR_NOT_IMPLEMENTED",
		2:  "ERROR_SERVICE_UNAVAILABLE",
		3:  "ERROR_INVALID_REQUEST",
		4:  "ERROR_INVALID_CONTENT_TYPE",
		5:  "ERROR_VALIDATION",
		6:  "ERROR_UNAUTHORIZED",
		7:  "ERROR_FORBIDDEN",
		8:  "ERROR_NOT_FOUND",
		9:  "ERROR_ALREADY_EXISTS",
		10: "ERROR_RESOURCE_CONFLICT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_INTERNAL":             0,
		"ERROR_NOT_IMPLEMENTED":      1,
		"ERROR_SERVICE_UNAVAILABLE":  2,
		"ERROR_INVALID_REQUEST":      3,
		"ERROR_INVALID_CONTENT_TYPE": 4,
		"ERROR_VALIDATION":           5,
		"ERROR_UNAUTHORIZED":         6,
		"ERROR_FORBIDDEN":            7,
		"ERROR_NOT_FOUND":            8,
		"ERROR_ALREADY_EXISTS":       9,
		"ERROR_RESOURCE_CONFLICT":    10,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_marketplace_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_marketplace_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{0}
}

// Status response message
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{0}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Error response message
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=marketplace.ErrorCode" json:"code,omitempty"` // Using the enum instead of string
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_INTERNAL
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_marketplace_proto protoreflect.FileDescriptor

const file_marketplace_proto_rawDesc = "" +
	"\n" +
	"\x11marketplace.proto\x12\vmarketplace\"`\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xd4\x01\n" +
	"\rErrorResponse\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.marketplace.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\adetails\x18\x03 \x03(\v2'.marketplace.ErrorResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xa3\x02\n" +
	"\tErrorCode\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10\x00\x12\x19\n" +
	"\x15ERROR_NOT_IMPLEMENTED\x10\x01\x12\x1d\n" +
	"\x19ERROR_SERVICE_UNAVAILABLE\x10\x02\x12\x19\n" +
	"\x15ERROR_INVALID_REQUEST\x10\x03\x12\x1e\n" +
	"\x1aERROR_INVALID_CONTENT_TYPE\x10\x04\x12\x14\n" +
	"\x10ERROR_VALIDATION\x10\x05\x12\x16\n" +
	"\x12ERROR_UNAUTHORIZED\x10\x06\x12\x13\n" +
	"\x0fERROR_FORBIDDEN\x10\a\x12\x13\n" +
	"\x0fERROR_NOT_FOUND\x10\b\x12\x18\n" +
	"\x14ERROR_ALREADY_EXISTS\x10\t\x12\x1b\n" +
	"\x17ERROR_RESOURCE_CONFLICT\x10\n" +
	"B\x13Z\x11marketplace/protob\x06proto3"

var (
	file_marketplace_proto_rawDescOnce sync.Once
	file_marketplace_proto_rawDescData []byte
)

func file_marketplace_proto_rawDescGZIP() []byte {
	file_marketplace_proto_rawDescOnce.Do(func() {
		file_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_proto_rawDesc), len(file_marketplace_proto_rawDesc)))
	})
	return file_marketplace_proto_rawDescData
}

var file_marketplace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_marketplace_proto_goTypes = []any{
	(ErrorCode)(0),         // 0: marketplace.ErrorCode
	(*StatusResponse)(nil), // 1: marketplace.StatusResponse
	(*ErrorResponse)(nil),  // 2: marketplace.ErrorResponse
	nil,                    // 3: marketplace.ErrorResponse.DetailsEntry
}
var file_marketplace_proto_depIdxs = []int32{
	0, // 0: marketplace.ErrorResponse.code:type_name -> marketplace.ErrorCode
	3, // 1: marketplace.ErrorResponse.details:type_name -> marketplace.ErrorResponse.DetailsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_marketplace_proto_init() }
func file_marketplace_proto_init() {
	if File_marketplace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_proto_rawDesc), len(file_marketplace_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marketplace_proto_goTypes,
		DependencyIndexes: file_marketplace_proto_depIdxs,
		EnumInfos:         file_marketplace_proto_enumTypes,
		MessageInfos:      file_marketplace_proto_msgTypes,
	}.Build()
	File_marketplace_proto = out.File
	file_marketplace_proto_goTypes = nil
	file_marketplace_proto_depIdxs = nil
}
